name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: Ming_Fong_Resume.tex
    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: Ming_Fong_Resume.pdf
